repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff
        args: ["check", "--fix"]
        language: system
        types_or: [python]
      - id: ruff-format
        name: ruff-format
        entry: ruff
        args: ["format"]
        language: system
        types_or: [python]
      - id: pytest
        name: pytest
        entry: pytest
        language: python
        language_version: python3.13
        pass_filenames: false
        additional_dependencies:
          - pytest
          - "rich>=14.1.0"
          - "textual>=3.2.0"
        stages: [commit]
        require_serial: true
